//const {} = require('./consts.js')

module.exports = {
	record_mode: [
		{ id: '00', label: 'Record' },
		{ id: '01', label: 'Record Ready' },
		{ id: '02', label: 'Track Mark' },
		{ id: '10', label: 'Input Monitor' },
	],
	jog_mode: [
		{ id: '00', label: 'OFF' },
		{ id: '01', label: 'ON' },
		{ id: '10', label: 'Jog Forward' },
		{ id: '11', label: 'Jog Reverse' },
	],
	shuttle_mode: [
		{ id: '00', label: 'Shuttle Forward' },
		{ id: '01', label: 'Shuttle Reverse' },
	],
	skip_mode: [
		{ id: '00', label: 'Track Skip Next' },
		{ id: '01', label: 'Track Skip Previous' },
		{ id: '20', label: 'Mark Skip Next' },
		{ id: '21', label: 'Mark Skip Previous' },
		{ id: '30', label: 'Time Skip Next' },
		{ id: '31', label: 'Time Skip Previous' },
	],
	autoCueLevelPreset_mode: [
		{ id: '00', label: '-24dB' },
		{ id: '01', label: '-30dB' },
		{ id: '02', label: '-36dB' },
		{ id: '03', label: '-42dB' },
		{ id: '04', label: '-48dB' },
		{ id: '05', label: '-54dB' },
		{ id: '06', label: '-60dB' },
		{ id: '07', label: '-66dB' },
		{ id: '08', label: '-72dB' },
		{ id: 'FF', label: 'SENSE' },
	],
	autoTrackLevelPreset_mode: [
		{ id: '00', label: '-24dB' },
		{ id: '01', label: '-30dB' },
		{ id: '02', label: '-36dB' },
		{ id: '03', label: '-42dB' },
		{ id: '04', label: '-48dB' },
		{ id: '05', label: '-54dB' },
		{ id: '06', label: '-60dB' },
		{ id: '07', label: '-66dB' },
		{ id: '08', label: '-72dB' },
		{ id: 'FF', label: 'SENSE' },
	],
	syncRecLevelPreset_mode: [
		{ id: '00', label: '-24dB' },
		{ id: '01', label: '-30dB' },
		{ id: '02', label: '-36dB' },
		{ id: '03', label: '-42dB' },
		{ id: '04', label: '-48dB' },
		{ id: '05', label: '-54dB' },
		{ id: '06', label: '-60dB' },
		{ id: '07', label: '-66dB' },
		{ id: '08', label: '-72dB' },
		{ id: 'FF', label: 'SENSE' },
	],
	autoCueSelect_mode: [
		{ id: '00', label: 'Auto-cue mode OFF' },
		{ id: '01', label: 'Auto-cue mode ON' },
		{ id: 'FF', label: 'Sense' },
	],
	autoTrackSelect_mode: [
		{ id: '00', label: 'Auto Track OFF' },
		{ id: '01', label: 'Auto Track ON (LEVEL)' },
		{ id: '02', label: 'Auto Track ON (Digital Direct)' },
		{ id: '03', label: 'Auto Track ON (TIME)' },
		{ id: '04', label: 'Auto Track ON (SIZE)' },
		{ id: 'FF', label: 'SENSE' },
	],
	pitchControlSelect_mode: [
		{ id: '00', label: 'Pitch control OFF' },
		{ id: '01', label: 'Pitch control ON' },
		{ id: 'FF', label: 'Sense' },
	],
	autoReadySelect_mode: [
		{ id: '00', label: 'Auto-ready OFF' },
		{ id: '01', label: 'Auto-ready ON' },
		{ id: 'FF', label: 'Sense' },
	],
	repeat_mode: [
		{ id: '00', label: 'Repeat OFF' },
		{ id: '01', label: 'Repeat ON' },
		{ id: 'FF', label: 'Sense' },
	],
	syncRecSelect_mode: [
		{ id: '00', label: 'Sync Rec OFF ' },
		{ id: '01', label: 'Sync Rec ON' },
		{ id: 'FF', label: 'Sense' },
	],
	incrPlay_mode: [
		{ id: '00', label: 'Incremental Playback OFF' },
		{ id: '01', label: 'Incremental Playback ON' },
		{ id: 'FF', label: 'Sense' },
	],
	keyControlSelect_mode: [
		{ id: '00', label: 'Key control mode OFF' },
		{ id: '01', label: 'Key control mode ON' },
		{ id: 'FF', label: 'Sense' },
	],
	remoteLocal_mode: [
		{ id: '00', label: 'Remote Only' },
		{ id: '01', label: 'Local and Remote' },
		{ id: 'FF', label: 'Sense' },
	],
	play_mode: [
		{ id: '00', label: 'Continuous' },
		{ id: '01', label: 'Single' },
		{ id: '04', label: 'Program' },
		{ id: '06', label: 'Random' },
	],
	specifiedDeviceStatusSense_mode: [
		{ id: '00', label: 'SD1' },
		{ id: '01', label: 'SD2' },
		{ id: '10', label: 'USB' },
		{ id: '11', label: 'CD' },
	],
	currentTrackTime_sense: [
		{ id: '00', label: 'Elapsed Time' },
		{ id: '01', label: 'Remain Time' },
		{ id: '02', label: 'Total Elapsed Time' },
		{ id: '03', label: 'Total Remain Time' },
	],
	powerControl_mode: [
		{ id: '00', label: 'Power On' },
		{ id: '11', label: 'Power Off' },
		{ id: '80', label: 'Reset' },
	],
	deviceSelect_mode: [
		{ id: '00', label: 'SD1' },
		{ id: '01', label: 'SD2' },
		{ id: '10', label: 'USB' },
		{ id: '11', label: 'CD' },
		{ id: 'FF', label: 'Sense' },
	],
	playArea_mode: [
		{ id: '00', label: 'All' },
		{ id: '01', label: 'Folder' },
		{ id: '02', label: 'Playlist' },
		{ id: 'FF', label: 'Sense' },
	],
	userWordSense_mode: [
		{ id: '10', label: 'USER01' },
		{ id: '11', label: 'USER02' },
		{ id: '12', label: 'USER03' },
		{ id: '13', label: 'USER04' },
		{ id: '14', label: 'USER05' },
	],
	fileNameSelect_mode: [
		{ id: '00', label: 'DATE/TIME' },
		{ id: '10', label: 'USER01' },
		{ id: '11', label: 'USER02' },
		{ id: '12', label: 'USER03' },
		{ id: '13', label: 'USER04' },
		{ id: '14', label: 'USER05' },
		{ id: 'FF', label: 'Sense' },
	],
	mediaFormat_mode: [
		{ id: '00', label: 'Quick Format' },
		{ id: '01', label: 'Full Format' },
	],
	inputSelect_mode: [
		{ id: '000000', label: 'ANALOG BALANCED' },
		{ id: '000001', label: 'ANALOG UNBALANCED' },
		{ id: '00100', label: 'DIGITAL XLR' },
		{ id: '000101', label: 'DIGITAL COAXIAL' },
		{ id: '000200', label: 'IF-DA2(DANTE)' },
		{ id: '00FF', label: 'Sense' },
	],
	//feedbacks
	autoCueLevelReturn_feedback: [
		{ id: '00', label: '-24dB' },
		{ id: '01', label: '-30dB' },
		{ id: '02', label: '-36dB' },
		{ id: '03', label: '-42dB' },
		{ id: '04', label: '-48dB' },
		{ id: '05', label: '-54dB' },
		{ id: '06', label: '-60dB' },
		{ id: '07', label: '-66dB' },
		{ id: '08', label: '-72dB' },
	],
	autoTrackLevelReturn_feedback: [
		{ id: '00', label: '-24dB' },
		{ id: '01', label: '-30dB' },
		{ id: '02', label: '-36dB' },
		{ id: '03', label: '-42dB' },
		{ id: '04', label: '-48dB' },
		{ id: '05', label: '-54dB' },
		{ id: '06', label: '-60dB' },
		{ id: '07', label: '-66dB' },
		{ id: '08', label: '-72dB' },
	],
	syncRecLevelReturn_feedback: [
		{ id: '00', label: '-24dB' },
		{ id: '01', label: '-30dB' },
		{ id: '02', label: '-36dB' },
		{ id: '03', label: '-42dB' },
		{ id: '04', label: '-48dB' },
		{ id: '05', label: '-54dB' },
		{ id: '06', label: '-60dB' },
		{ id: '07', label: '-66dB' },
		{ id: '08', label: '-72dB' },
	],
	autoCueReturn_feedback: [
		{ id: '00', label: 'Auto-cue mode OFF' },
		{ id: '01', label: 'Auto-cue mode ON' },
	],
	autoTrackReturn_feedback: [
		{ id: '00', label: 'Auto Track OFF' },
		{ id: '01', label: 'Auto Track ON (LEVEL)' },
		{ id: '02', label: 'Auto Track ON (Digital Direct)' },
		{ id: '03', label: 'Auto Track ON (TIME)' },
		{ id: '04', label: 'Auto Track ON (SIZE)' },
	],
	pitchControlReturn_feedback: [
		{ id: '00', label: 'Pitch control OFF' },
		{ id: '01', label: 'Pitch control ON' },
	],
	autoReadyReturn_feedback: [
		{ id: '00', label: 'Auto-ready OFF' },
		{ id: '01', label: 'Auto-ready ON' },
	],
	repeat_feedback: [
		{ id: '00', label: 'Repeat OFF' },
		{ id: '01', label: 'Repeat ON' },
	],
	syncRecReturn_feedback: [
		{ id: '00', label: 'Sync Rec OFF ' },
		{ id: '01', label: 'Sync Rec ON' },
	],
	incrPlay_feedback: [
		{ id: '00', label: 'Incremental Playback OFF' },
		{ id: '01', label: 'Incremental Playback ON' },
	],
	remoteLocal_feedback: [
		{ id: '00', label: 'Remote Only' },
		{ id: '01', label: 'Local and Remote' },
	],
	play_feedback: [
		{ id: '00', label: 'Continuous' },
		{ id: '01', label: 'Single' },
		{ id: '04', label: 'Program (data not available)' },
		{ id: '05', label: 'Program (data available)' },
		{ id: '06', label: 'Random' },
	],
	mechaStatus_feedback: [
		{ id: '00', label: 'No Media' },
		{ id: '01', label: 'Preparing for disc ejection' },
		{ id: '10', label: 'Stop' },
		{ id: '11', label: 'Play' },
		{ id: '12', label: 'Ready On (Pause)' },
		{ id: '28', label: 'Cue - Searching forward' },
		{ id: '29', label: 'Review - Searching backward' },
		{ id: '80', label: 'Monitor' },
		{ id: '81', label: 'Record' },
		{ id: '82', label: 'Record Pause' },
		{ id: '83', label: 'Information Writing' },
		{ id: 'FF', label: 'Other' },
	],
	specifiedDeviceStatus_device_feedback: [
		{ id: '00', label: 'SD1' },
		{ id: '01', label: 'SD2' },
		{ id: '10', label: 'USB' },
		{ id: '11', label: 'CD' },
	],
	specifiedDeviceStatus_status_feedback: [
		{ id: '00', label: 'No Media' },
		{ id: '01', label: 'Preparing for disc ejection' },
		{ id: '10', label: 'Stop' },
		{ id: '11', label: 'Play' },
		{ id: '12', label: 'Ready On (Pause)' },
		{ id: '28', label: 'Cue - Searching forward' },
		{ id: '29', label: 'Review - Searching backward' },
		{ id: '80', label: 'Monitor' },
		{ id: '81', label: 'Record' },
		{ id: '82', label: 'Record Pause' },
		{ id: '83', label: 'Information Writing' },
		{ id: 'FF', label: 'Other' },
	],
	mediaStatusReturn_mediaStatus_feedback: [
		{ id: '00', label: 'No Media' },
		{ id: '01', label: 'Media Loaded' },
	],
	mediaStatusReturn_mediaType_feedback: [
		{ id: '00', label: 'CD-DA' },
		{ id: '01', label: 'CD-R (Audio)' },
		{ id: '02', label: 'CD-RW (Audio)' },
		{ id: '10', label: 'CD-ROM (Data)' },
		{ id: '11', label: 'CD-R (Data)' },
		{ id: '12', label: 'CD-RW (Data)' },
	],
	keyboardTypeReturn_feedback: [
		{ id: '00', label: 'Japanese' },
		{ id: '01', label: 'US' },
	],
	errorSense_feedback: [
		{ id: '0-00', label: 'No Error' },
		{ id: '0-01', label: 'Rec Error' },
		{ id: '1-02', label: 'Device Error' },
		{ id: '1-08', label: 'Stand-By Error' },
		{ id: '1-09', label: 'Information Write Error' },
		{ id: '1-FF', label: 'Other Error' },
	],
	cautionSense_feedback: [
		{ id: '0-00', label: 'No Caution' },
		{ id: '1-02', label: 'Media Error' },
		{ id: '1-03', label: "Can't Undo" },
		{ id: '1-06', label: 'Media Full' },
		{ id: '1-07', label: 'Track Full' },
		{ id: '1-09', label: 'Digital In Unlock' },
		{ id: '1-0A', label: 'No Call Point' },
		{ id: '1-0B', label: "Can't REC" },
		{ id: '1-0C', label: 'Write Protected' },
		{ id: '1-0D', label: 'Not Execute' },
		{ id: '1-0F', label: "Can't Edit" },
		{ id: '1-13', label: "Can't Select" },
		{ id: '1-14', label: 'Track Protected' },
		{ id: '1-16', label: 'Name Full' },
		{ id: '1-18', label: 'Play List Error' },
		{ id: '1-1D', label: 'Not Audio' },
		{ id: '1-1E', label: 'Decode Error' },
		{ id: '1-1F', label: 'Media Not Match' },
		{ id: '1-FF', label: 'Other Caution' },
	],
	deviceSelect_feedback: [
		{ id: '00', label: 'SD1' },
		{ id: '01', label: 'SD2' },
		{ id: '10', label: 'USB' },
		{ id: '11', label: 'CD' },
	],
	playArea_feedback: [
		{ id: '00', label: 'All' },
		{ id: '01', label: 'Folder' },
		{ id: '02', label: 'Playlist' },
	],
	userWordPresetReturn_feedback: [
		{ id: '10', label: 'USER01' },
		{ id: '11', label: 'USER02' },
		{ id: '12', label: 'USER03' },
		{ id: '13', label: 'USER04' },
		{ id: '14', label: 'USER05' },
	],
	fileNameSelectReturn_feedback: [
		{ id: '00', label: 'DATE/TIME' },
		{ id: '10', label: 'USER01' },
		{ id: '11', label: 'USER02' },
		{ id: '12', label: 'USER03' },
		{ id: '13', label: 'USER04' },
		{ id: '14', label: 'USER05' },
	],
	mediaFormatAck_feedback: [
		{ id: '00', label: 'Start' },
		{ id: '11', label: 'END - OK' },
		{ id: '12', label: 'END - NOT OK' },
	],
	inputSelect_feedback: [
		{ id: '000000', label: 'ANALOG BALANCED' },
		{ id: '000001', label: 'ANALOG UNBALANCED' },
		{ id: '00100', label: 'DIGITAL XLR' },
		{ id: '000101', label: 'DIGITAL COAXIAL' },
		{ id: '000200', label: 'IF-DA2(DANTE)' },
	],
	renameFolderAck_feedback: [
		{ id: '00', label: 'Start' },
		{ id: '11', label: 'END - OK' },
		{ id: '12', label: 'END - NOT OK' },
	],
}
