export const msgDelay = 20 // Make sure that commands are sent at a minimum of 20-millisecond intervals.
export const keepAliveInterval = 1000
export const timeOutInterval = 15000
export const SOM = '0'
export const EOM = '\r\n'
export const EndSession = 'exit'
export const cmd = {
	infoReq: '0F',
	stop: '10',
	play: '12',
	record: '13',
	pause: '14', //ready
	jog: '15',
	shuttle: '16',
	flashLoad: '17',
	eject: '18',
	skip: '1A',
	call: '1D',
	autoCueLevelPreset: '20',
	autoTrackLevelPreset: '21',
	directTrackSearchPreset: '23',
	pitchControlDataPreset: '25',
	autoTrackTimePreset: '26',
	clockDataPreset: '27',
	syncRecLevelPreset: '28',
	textPreset: '29',
	timeSearchPreset: '2C',
	keyControlDataPreset: '2D',
	autoCueSelect: '30',
	autoTrackSelect: '31',
	eomTrackTimePreset: '32',
	eomMediaTimePreset: '33',
	pitchControlSelect: '35',
	autoReadySelect: '36',
	repeatModeSelect: '37',
	syncRecSelect: '38',
	incrPlaySelect: '3A',
	keyControlSelect: '3D',
	remoteLocalModeSelect: '4C',
	playModeSelect: '4D',
	playModeSense: '4E',
	mechaStatusSense: '50',
	specifiedDeviceStatusSense: '51',
	trackNumSense: '55',
	mediaStatusSense: '56',
	currentTrackInfoSense: '57',
	currentTrackTimeSense: '58',
	nameSense: '59',
	totalTrackNoTotalTimeSense: '5D',
	pgmTotalTrackNoTotalTimeSense: '5E',
	keyboardTypeSense: '5F',
	powerControl: '75',
	errorSense: '78',
	cautionSense: '79',
	vendorCommand: '7F',
	deviceSelect: '7F01',
	divide: '7F02',
	delete: '7F03',
	timeSkipPreset: '7F0701',
	timeSkipSense: '7F0702',
	playAreaSelect: '7F074F',
	autoTrackSizePreset: '7F0823',
	userWordPreset: '7F082A',
	userWordSense: '7F085A',
	fileNameSelect: '7F0860',
	currentMediaRecordableTimeSense: '7F1010',
	mediaFormat: '7F1044',
	inputSelect: '7F1210',
	fileRename: '7F4200',
	currentFolderSelect: '7F4A23',
	createFolder: '7F4A40',
	renameFolder: '7F4A42',
	currentFolderNoSense: '7F4A55',
	searchFolderNo: '7F4A56',
	folderNameSense: '7F4A59',
	folderCountSense: '7F4A5D',
	fileCountSense: '7F4A5E',
}

export const resp = {
	password: 'Enter Password',
	loginSuccess: 'Login Successful',
	loginFail: 'Password is different',
	keepAlive: 'FA',
	infoReturn: '8F',
	flashLoadAck: '97',
	autoCueLevelReturn: 'A0',
	autoTrackLevelReturn: 'A1',
	pitchControlDataReturn: 'A5',
	autoTrackTimeReturn: 'A6',
	clockDateReturn: 'A7',
	syncRecLevelReturn: 'A8',
	keyControlDataReturn: 'AD',
	autoCueSelectReturn: 'B0',
	autoTrackSelectReturn: 'B1',
	eomTrackTimeReturn: 'B2',
	eomMediaTimeReturn: 'B3',
	pitchControlSelectReturn: 'B5',
	autoReadySelectReturn: 'B6',
	repeatSelectReturn: 'B7',
	syncRecSelectReturn: 'B8',
	incrPlaySelectReturn: 'BA',
	remoteLocalModeReturn: 'CC',
	playModeReturn: 'CE',
	mechaStatusReturn: 'D0',
	specifiedDeviceStatusReturn: 'D1',
	trackNoStatusReturn: 'D5',
	mediaStatusReturn: 'D6',
	trackCurrentInfoReturn: 'D7',
	trackCurrentTimeReturn: 'D8',
	nameReturn: 'D9',
	totalTrackNoTotalTimeReturn: 'DD',
	pgmTotalTrackNoTotalTimeReturn: 'DE',
	keyboardTypeReturn: 'DF',
	errorSenseRequest: 'F0',
	cautionSenseRequest: 'F1',
	illegalStatus: 'F2',
	powerOnStatus: 'F4',
	changeStatus: 'F6',
	powerControlReturn: 'F5',
	errorSenseReturn: 'F8',
	cautionSenseReturn: 'F9',
	venderCommandReturn: 'FF',
	deviceSelectReturn: 'FF01',
	timeSkipReturn: 'FF0702',
	playAreaSelectReturn: 'FF07CF',
	autoTrackSizeReturn: 'FF08A3',
	userWordPresetReturn: 'FF082A',
	userWordSenseReturn: 'FF08DA',
	fileNameSelectReturn: 'FF08E0',
	currentMediaRecordableTimeReturn: 'FF1090',
	mediaFormatAck: 'FF10C4',
	inputSelectReturn: 'FF1290',
	fileRenameAck: 'FF4280',
	createFolderAck: 'FF4AC0',
	renameFolderAck: 'FF4AC2',
	currentFolderNoReturn: 'FF4AD5',
	searchFolderNoReturn: 'FF4AD6',
	folderNameReturn: 'FF4AD9',
	fileNameReturn: 'FF4ADA',
	folderCountReturn: 'FF4ADD',
	fileCountReturn: 'FF4ADE',
}

export const respParam = {
	mechaStatusReturn: {
		noMedia: '00',
		stop: '10',
		play: '11',
		readyOn: '12',
		cue: '28',
		review: '29',
		record: '81',
		recordReady: '82',
		infomationWriting: '83',
		other: 'FF',
	},
}

export const cmdOnLogin = [
	cmd.errorSense,
	cmd.cautionSense,
	cmd.mechaStatusSense,
	cmd.trackNumSense,
	cmd.deviceSelect + 'FF',
	cmd.repeatModeSelect + 'FF',
	cmd.resumePlaySelect + 'FF',
	cmd.incrPlaySelect + 'FF',
	cmd.remoteLocalModeSelect + 'FF',
	cmd.playModeSelect + 'FF',
	cmd.playAreaSelect + 'FF',
]

export const cmdOnKeepAlive = [cmd.mechaStatusSense, cmd.trackNumSense, cmd.currentTrackInfoSense]
